sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
        settings:
            routes:
                list: app.get_settings
                detail: app.get_setting
sulu_core:
    locales:
        en: English
        nl: Dutch
    translations:
        - en
        - nl
