image: ciryk/ci:7.3-apache
stages:
  - style
  - staging
  - deploy

stylelint:
  stage: style
  before_script:
    - cd assets/website
  script:
    - npm run stylelint
  only:
    changes:
      - assets/website/**/*.scss

eslint:
  stage: style
  before_script:
    - cd assets/website
  script:
    - npm run eslint
  only:
    changes:
      - assets/website/**/*.js
