image: ciryk/ci:7.3-apache
stages:
  - style
  - staging
  - deploy

stylelint:
  stage: style
  before_script:
    - cd assets/website
  script:
    - npm run stylelint

eslint:
  stage: style
  before_script:
    - cd assets/website
  script:
    - npm run eslint

twig:
  stage: style
  before_script:
    - composer install
  script:
    - php bin/websiteconsole lint:twig templates
