image: ciryk/ci:7.3-apache
stages:
  - style

stylelint:
  stage: style
  before_script:
    - cd assets/website
  script:
    - npm run stylelint

eslint:
  stage: style
  before_script:
    - cd assets/website
  script:
    - npm run eslint
