version: '3.1'
services:
  app:
    image: ciryk/dev:7.3-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:cached
      - vendor:/var/www/html/vendor
      - cache:/var/www/html/var/cache
      - log:/var/www/html/var/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sulu
      MYSQL_ROOT_PASSWORD: sulu
    volumes:
      - my-db:/var/lib/mysql
  mail:
    image: tophfr/mailcatcher
    ports:
      - "1080:80"
volumes:
  my-db:
  vendor:
  cache:
  log:
