version: '3.1'
services:
  app:
    image: ciryk/dev:7.3-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:cached
      - vendor:/var/www/html/vendor
    depends_on:
      - db
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sulu
      MYSQL_ROOT_PASSWORD: sulu
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
  vendor:
