# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    default_locale: nl
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add controllers as services that are specific to a certain sulu context
    # a sulu context is a different mode in the kernel allowing to have a different set of services
    # because controllers might rely on services only existing in one of both contexts
    App\Controller\Admin\:
        resource: '../src/Controller/Admin'
        tags: ['controller.service_arguments', {name: 'sulu.context', context: 'admin'}]

    App\Controller\Website\:
        resource: '../src/Controller/Website'
        tags: ['controller.service_arguments', {name: 'sulu.context', context: 'website'}]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    sulu_form.configuration.form_configuration_factory:
        class: App\Configuration\FormConfigurationFactory
        arguments:
            - '@sulu_form.media_collection_strategy.default'
            - '%sulu_form.mail.template.notify%'
            - '%sulu_form.mail.template.customer%'
            - '%sulu_form.mail.template.notify_plain_text%'
            - '%sulu_form.mail.template.customer_plain_text%'
            - '@sulu_document_manager.document_manager'
    sulu_form.list_builder.dynamic_list_builder:
        class: App\Form\ListBuilder\DynamicListBuilder
        arguments:
            - '%sulu_form.dynamic_list_builder.delimiter%'
            - '@router'
            - '@sulu_document_manager.document_manager'
        tags:
            - { name: 'sulu_form.dynamic_list_builder', alias: 'simple' }
    sulu_form.list_builder.dynamic_list_factory:
        class: App\Form\ListBuilder\DynamicListFactory
        arguments:
            - '%sulu_form.dynamic_list_builder.default%'
